#!/usr/bin/env bash
set -euo pipefail

# macOS-only dev installer for Flow + local Jazz/Groove.
# Clones Flow + Jazz, patches Cargo to use local groove crates, builds, and
# symlinks binaries into ~/.local/bin.

fail() {
  echo "flow macos dev install: $*" >&2
  exit 1
}

info() {
  echo "flow macos dev install: $*"
}

if [[ "$(uname -s)" != "Darwin" ]]; then
  fail "this script is macOS-only"
fi

BASE_DIR="${FLOW_DEV_ROOT:-$HOME/code/org/1f}"
FLOW_REPO_URL="${FLOW_REPO_URL:-https://github.com/nikivdev/flow}"
JAZZ_REPO_URL="${FLOW_JAZZ_URL:-https://github.com/1focus-ai/jazz}"
FLOW_DIR="${FLOW_DEV_FLOW_DIR:-$BASE_DIR/flow}"
JAZZ_DIR="${FLOW_DEV_JAZZ_DIR:-$BASE_DIR/jazz}"
BIN_DIR="${FLOW_BIN_DIR:-$HOME/.local/bin}"

ensure_brew() {
  if command -v brew >/dev/null 2>&1; then
    return 0
  fi
  info "installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  if [[ -f "/opt/homebrew/bin/brew" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [[ -f "/usr/local/bin/brew" ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
  fi
}

ensure_fnm_and_node() {
  if ! command -v fnm >/dev/null 2>&1; then
    info "installing fnm..."
    brew install fnm
  fi

  # Ensure fnm is active in this shell
  eval "$(fnm env)"

  if ! command -v node >/dev/null 2>&1; then
    info "installing Node.js (LTS) via fnm..."
    install_out="$(fnm install --lts 2>&1)" || fail "fnm install --lts failed"
    echo "$install_out"
    installed_version="$(printf "%s\n" "$install_out" | grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+' | tail -n1 || true)"
    if [[ -n "${installed_version}" ]]; then
      fnm default "${installed_version}" || true
    fi
  fi
}

ensure_rust() {
  if command -v cargo >/dev/null 2>&1; then
    return 0
  fi
  info "installing Rust..."
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  # shellcheck disable=SC1090
  source "$HOME/.cargo/env"
}

clone_or_update() {
  mkdir -p "${BASE_DIR}"

  if [[ -d "${JAZZ_DIR}/.git" ]]; then
    info "updating Jazz..."
    (cd "${JAZZ_DIR}" && git pull --rebase) || true
  else
    info "cloning Jazz to ${JAZZ_DIR}..."
    git clone "${JAZZ_REPO_URL}" "${JAZZ_DIR}"
  fi

  if [[ -d "${FLOW_DIR}/.git" ]]; then
    info "updating Flow..."
    (cd "${FLOW_DIR}" && git pull --rebase) || true
  else
    info "cloning Flow to ${FLOW_DIR}..."
    git clone "${FLOW_REPO_URL}" "${FLOW_DIR}"
  fi
}

write_cargo_patch() {
  mkdir -p "${FLOW_DIR}/.cargo"
  cat > "${FLOW_DIR}/.cargo/config.toml" <<EOF
# Local path overrides for faster builds (auto-generated by install-macos-dev.sh)
[patch."https://github.com/1focus-ai/jazz"]
groove = { path = "${JAZZ_DIR}/crates/groove" }
groove-rocksdb = { path = "${JAZZ_DIR}/crates/groove-rocksdb" }
EOF
}

build_and_link() {
  info "building Flow..."
  (cd "${FLOW_DIR}" && cargo build --release)

  mkdir -p "${BIN_DIR}"
  ln -sf "${FLOW_DIR}/target/release/f" "${BIN_DIR}/f"
  ln -sf "${FLOW_DIR}/target/release/f" "${BIN_DIR}/flow"
  if [[ -f "${FLOW_DIR}/target/release/lin" ]]; then
    ln -sf "${FLOW_DIR}/target/release/lin" "${BIN_DIR}/lin"
  fi
}

ensure_shell_setup() {
  local zshrc="$HOME/.zshrc"
  local bashrc="$HOME/.bashrc"
  local bash_profile="$HOME/.bash_profile"

  local path_line="export PATH=\"${BIN_DIR}:\$PATH\""
  local fnm_line='eval "$(fnm env --use-on-cd)"'

  if [[ -f "${zshrc}" ]]; then
    grep -qF "${path_line}" "${zshrc}" || echo "${path_line}" >> "${zshrc}"
    grep -qF "${fnm_line}" "${zshrc}" || echo "${fnm_line}" >> "${zshrc}"
  elif [[ -f "${bashrc}" ]]; then
    grep -qF "${path_line}" "${bashrc}" || echo "${path_line}" >> "${bashrc}"
    grep -qF "${fnm_line}" "${bashrc}" || echo "${fnm_line}" >> "${bashrc}"
  elif [[ -f "${bash_profile}" ]]; then
    grep -qF "${path_line}" "${bash_profile}" || echo "${path_line}" >> "${bash_profile}"
    grep -qF "${fnm_line}" "${bash_profile}" || echo "${fnm_line}" >> "${bash_profile}"
  else
    info "add to your shell config:"
    info "  ${path_line}"
    info "  ${fnm_line}"
  fi
}

main() {
  info "starting macOS dev install"
  ensure_brew
  ensure_fnm_and_node
  ensure_rust
  clone_or_update
  write_cargo_patch
  build_and_link
  ensure_shell_setup

  info ""
  info "done."
  info "flow: ${FLOW_DIR}"
  info "jazz: ${JAZZ_DIR}"
  info "bin: ${BIN_DIR}"
  info "restart your shell, then run: f --help"
}

main "$@"
