pub mod agent_setup;
pub mod agents;
pub mod ai;
pub mod ai_context;
pub mod ai_everruns;
pub mod ai_server;
pub mod ai_taskd;
pub mod ai_tasks;
pub mod ai_test;
pub mod analytics;
pub mod archive;
pub mod ask;
pub mod auth;
pub mod base_tool;
pub mod branches;
pub mod changes;
pub mod cli;
pub mod code;
pub mod commit;
pub mod commits;
pub mod config;
pub mod daemon;
pub mod db;
pub mod deploy;
pub mod deploy_setup;
pub mod deps;
pub mod discover;
pub mod docs;
pub mod doctor;
pub mod domains;
pub mod env;
pub mod env_setup;
pub mod explain_commits;
pub mod ext;
pub mod features;
pub mod fish_install;
pub mod fish_trace;
pub mod fix;
pub mod fixup;
pub mod flox;
pub mod gh_release;
pub mod git_guard;
pub mod gitignore_policy;
pub mod hash;
pub mod health;
pub mod help_search;
pub mod history;
pub mod hive;
pub mod home;
pub mod hub;
pub mod info;
pub mod init;
pub mod install;
pub mod invariants;
#[path = "jazz_state_stub.rs"]
pub mod jazz_state;
pub mod jj;
pub mod latest;
pub mod lifecycle;
pub mod lmstudio;
pub mod log_server;
pub mod log_store;
pub mod macos;
pub mod notify;
pub mod opentui_prompt;
pub mod otp;
pub mod palette;
pub mod parallel;
pub mod pr_edit;
pub mod processes;
pub mod projects;
pub mod proxy;
pub mod publish;
pub mod push;
pub mod recipe;
pub mod registry;
pub mod release;
pub mod release_signing;
pub mod repos;
pub mod reviews_todo;
pub mod running;
pub mod sealer_crypto;
pub mod secret_redact;
pub mod seq_client;
pub mod seq_rpc;
pub mod services;
pub mod setup;
pub mod skills;
pub mod ssh;
pub mod ssh_keys;
pub mod start;
pub mod storage;
pub mod supervisor;
pub mod sync;
pub mod task_failure_agents;
pub mod task_match;
pub mod tasks;
pub mod todo;
pub mod tools;
#[path = "traces_stub.rs"]
pub mod traces;
pub mod undo;
pub mod upgrade;
pub mod upstream;
pub mod usage;
pub mod vcs;
pub mod watchers;
pub mod web;

/// Initialize tracing with a default filter if `RUST_LOG` is unset.
pub fn init_tracing() {
    let default_filter = "flowd=info,axum=warn,tower=warn";
    let filter_layer = std::env::var("RUST_LOG").unwrap_or_else(|_| default_filter.to_string());

    tracing_subscriber::fmt()
        .with_env_filter(filter_layer)
        .with_target(false)
        .compact()
        .init();
}
